version: '3.9'

services:
  api_products:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=todos
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_USER: MarioIbarra
      MYSQL_PASSWORD: MarioIbarra

volumes:
  mysql_data: