version: '3.9'

services:
  db:
    image: mysql:8.0.32
    ports:
      - "3000:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: MarioIbarra
      MYSQL_PASSWORD: MarioIbarra

volumes:
  mysql_data: